name: ExtractionEvent
version: "${project.version}"
main: com.criztiandev.extractionevent.ExtractionEventPlugin
api-version: "1.21"
author: criztiandev
description: A Minecraft plugin for extraction event mechanics.
website: https://github.com/criztiandev/extraction-event

commands:
  lev:
    description: Main command for Lev regions.
    usage: /lev <wand|create|remove|list>
    aliases: [ee, extractionevent]
